### ISSUE TITLE
Construir la parte 1 del proyecto

### ISSUE THREAD

**Issue by Gr17Eq1** [Gr17Eq1/InmobiliariaHC#12]
Construir el datasource y todos los modelos y repositorios 
Dejar ese trabajo en su rama en GitHub
Hacer copia en la rama principal

**Comment by jhobando** [comment]
Se crearon los modelos de las entidades:
Persona
Asesor
Propietario
Cliente
Administrador
Inmueble
Solicitud
Venta
Alquiler
Codeudor

Dentro de las propiedades de cada entidad no se incluyeron las id foráneas pues esta se crean automáticamente en el momento de crear las relaciones.

> Todas las propiedades fueron de tipo string y necesarias
> La propiedad "id" en todos los casos se dejó como la propiedad ID para la base de datos y se genera automáticamente 
> La propiedad "valor" de "inmueble" es la única de tipo numérico
>Todas las entidades se nombran con mayúscula inicial y todas las propiedades en minuscula, sin espacios ni guiones
