### ISSUE TITLE
Construir la parte 2 del proyecto a partir de la construcción de la parte 1

### ISSUE THREAD

**Issue by Gr17Eq1** [Gr17Eq1/InmobiliariaHC#13]
Clonar el proyecto desde la rama principal
Completar la construcción con las relaciones, los servicios y los controladores
Dejar en su rama el proyecto y copiarla a la rama principal

**Comment by ghost** [comment]
#16 Se generaron los repositorio, relaciones y controladores entre las respectivas colecciones para su proceso de mapeo a la base de datos
